CREATE DATABASE IF NOT EXISTS INVENTARIO CHAR SET utf8mb3 COLLATE utf8mb3_spanish2_ci;
use inventario;

CREATE TABLE IF NOT EXISTS Usuarios(
ID INT AUTO_INCREMENT PRIMARY KEY,
PASS BINARY(32),
Email VARCHAR(30),
Username VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS Productos(
ID INT AUTO_INCREMENT PRIMARY KEY,
PRODUCTO VARCHAR(30),
STOCK INT,
ULTIMA_ACTUALIZACION DATETIME,
Username INT,
FOREIGN KEY(Username) references Usuarios(ID)
);